name: simpletodo
description: SimpleTodo App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get: ^4.5.1

  # firebase
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  uuid: ^3.0.5

  # google sign in
  google_sign_in: ^5.2.1

  # 환경변수
  flutter_dotenv: ^5.0.2

  # 로깅
  logger: ^1.1.0

  # json
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  json_serializable:
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - images/
    - dev.env

  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: fonts/NanumSquareRoundOTFL.otf
        - asset: fonts/NanumSquareRoundOTFR.otf
        - asset: fonts/NanumSquareRoundOTFB.otf
        - asset: fonts/NanumSquareRoundOTFEB.otf
